INSERT INTO users (ID, LASTNAME ,FIRSTNAME ,USERNAME ,PASSWORD ,CONFIRMPASSWORD ,FACULTY ) VALUES (0,'alma','alma','alma','pass','pass','2');
INSERT INTO users (ID, LASTNAME ,FIRSTNAME ,USERNAME ,PASSWORD ,CONFIRMPASSWORD ,FACULTY ) VALUES (1,'1','1','1','1','1','2');
INSERT INTO users (ID, LASTNAME ,FIRSTNAME ,USERNAME ,PASSWORD ,CONFIRMPASSWORD ,FACULTY ) VALUES (2,'2','2','2','2','2','2');

INSERT INTO SEMESTERS(ID,SEMESTER,SUBJECTS,USERNAME) VALUES(1,'1','Lineáris Algebra','alma');
INSERT INTO SEMESTERS(ID,SEMESTER,SUBJECTS,USERNAME) VALUES(2,'1','Lineáris Algebra','alma');



